# Generated by Django 3.1.7 on 2021-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210330_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='car_ownership',
            new_name='carownership',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='owner_ownership',
            new_name='ownerships',
        ),
        migrations.AddField(
            model_name='owner',
            name='ownerships',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Car'),
        ),
    ]
